"""
Diet Plan Panel Component.
Renders the center "Personalized Diet Plan" panel from the PDF UI mockup:
  - Day navigation (Previous / Day N / Next)
  - Meal cards: Breakfast, Lunch, Snack, Dinner
  - Download Full Report (PDF) button
  - Placeholder state for Week 7–8 (diet plan not yet generated)
"""

import streamlit as st
from typing import Optional
from uuid import UUID

from app.db.models import MedicalReport, DietPlan


# ── Meal display config ────────────────────────────────────────────────────────
MEAL_CONFIG = {
    "breakfast": ("🌅", "Breakfast"),
    "lunch":     ("☀️", "Lunch"),
    "snack":     ("🍎", "Snack"),
    "dinner":    ("🌙", "Dinner"),
}

# ── Sample plan shown as a preview until the real generator is built ───────────
SAMPLE_PLAN = {
    1: {
        "breakfast": "Oatmeal with skim milk, green tea",
        "lunch":     "Grilled chicken salad with olive oil dressing",
        "snack":     "Apple slices, almonds",
        "dinner":    "Steamed fish, steamed vegetables",
    },
    2: {
        "breakfast": "Vegetable smoothie, whole grain toast",
        "lunch":     "Quinoa salad with legumes",
        "snack":     "Low-fat yogurt, berries",
        "dinner":    "Grilled tofu with spinach",
    },
    3: {
        "breakfast": "Scrambled eggs (2), multigrain bread, orange juice",
        "lunch":     "Lentil soup, brown rice, cucumber salad",
        "snack":     "Walnuts, 1 pear",
        "dinner":    "Baked salmon, roasted broccoli, sweet potato",
    },
}

TOTAL_DAYS = len(SAMPLE_PLAN)


def _meal_card(meal_key: str, content: Optional[str]) -> None:
    """Render a single meal card."""
    icon, label = MEAL_CONFIG[meal_key]

    if content:
        body_html = f'<div class="meal-items">{content}</div>'
    else:
        body_html = '<div class="meal-coming-soon">Generated by AI — Week 7–8</div>'

    st.markdown(
        f"""
        <div class="meal-card">
            <div class="meal-card-header">
                <span class="meal-icon">{icon}</span>
                <span class="meal-label">{label}</span>
            </div>
            {body_html}
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_diet_plan_panel(
    report: Optional[MedicalReport],
    diet_plan: Optional[DietPlan] = None,
) -> None:
    """
    Render the center Diet Plan panel.

    Args:
        report:    Currently selected MedicalReport (used to check if data exists).
        diet_plan: A DietPlan ORM object if one has been generated (None until Week 7–8).
    """
    st.markdown(
        '<div class="panel-title">🥗 PERSONALIZED DIET PLAN</div>',
        unsafe_allow_html=True,
    )

    # ── Day State ─────────────────────────────────────────────────────
    if "diet_day" not in st.session_state:
        st.session_state["diet_day"] = 1

    current_day: int = st.session_state["diet_day"]

    # ── Day Navigation ────────────────────────────────────────────────
    col_prev, col_label, col_next = st.columns([2, 3, 2])

    with col_prev:
        prev_disabled = current_day <= 1
        if st.button(
            "◀ Prev",
            disabled=prev_disabled,
            use_container_width=True,
            key="btn_prev_day",
        ):
            st.session_state["diet_day"] -= 1
            st.rerun()

    with col_label:
        st.markdown(
            f'<div style="text-align:center;padding:6px 0;">'
            f'<span class="day-badge">Day {current_day} of {TOTAL_DAYS}</span>'
            f'</div>',
            unsafe_allow_html=True,
        )

    with col_next:
        next_disabled = current_day >= TOTAL_DAYS
        if st.button(
            "Next ▶",
            disabled=next_disabled,
            use_container_width=True,
            key="btn_next_day",
        ):
            st.session_state["diet_day"] += 1
            st.rerun()

    st.markdown('<hr class="section-divider">', unsafe_allow_html=True)

    # ── Resolve meal data ─────────────────────────────────────────────
    # Priority: real diet_plan JSON → sample plan → placeholders
    if diet_plan and diet_plan.plan_data:
        day_data = diet_plan.plan_data.get(str(current_day), {})
    elif report:
        # Show sample plan as a preview
        day_data = SAMPLE_PLAN.get(current_day, {})
        st.caption("📌 *Preview data — personalized plan generated in Week 7–8*")
    else:
        day_data = {}
        st.info("Select a processed report to preview the diet plan.")

    # ── Meal Cards ────────────────────────────────────────────────────
    for meal_key in ("breakfast", "lunch", "snack", "dinner"):
        _meal_card(meal_key, day_data.get(meal_key))

    st.markdown('<hr class="section-divider">', unsafe_allow_html=True)

    # ── Download CTA ──────────────────────────────────────────────────
    if diet_plan and diet_plan.plan_data:
        # Real download — available in Week 7–8
        st.download_button(
            label="⬇️ Download Full Report (PDF)",
            data=b"",          # replaced by real PDF bytes in Week 7-8
            file_name="DietPlan.pdf",
            mime="application/pdf",
            use_container_width=True,
        )
    else:
        st.button(
            "⬇️ Download Full Report (PDF)",
            use_container_width=True,
            disabled=True,
            help="PDF export is enabled after diet plan generation (Week 7–8)",
            key="btn_download_disabled",
        )